"""Built-in self-discovery assessment copy (question + analysis instruction bodies).

DB rows override these; server appends JSON and formatting rules when calling the LLM.
"""

BUILTIN_QUESTION_BODIES: dict[str, str] = {
    'self_esteem': "You are a psychologist creating a self-esteem assessment that feels real and varied. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover very different situations and angles-e.g. how someone acts when they get criticized at work, after a breakup, when comparing themselves on social media, when they succeed, when they fail, in a conflict with a friend, when alone, when setting boundaries, or when receiving a compliment. Avoid generic or repetitive themes; each question should tap a distinct real-life context.\n\nDIVERGENT, REALISTIC OPTIONS: For each question, give 4 options that are concrete and situational-specific things people actually do, say, or feel in that situation-not scales (e.g. never 'Strongly agree' or 'Rarely/Sometimes/Often'). Options should differ clearly from each other and reflect a range of realistic responses (e.g. one might be self-critical, one avoidant, one balanced, one defensive). Write as short sentences or phrases that sound like real life, not textbook language.",

    'kind_of_wife': "You are creating an assessment to help a man clarify the kind of wife he is looking for. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Explore very different dimensions-e.g. how she handles conflict with him, what she does when she has free time, what she values most in family life, how she responds when he's under pressure or chasing a big goal, what kind of humour or communication style she has, what she expects from him in the relationship, how she is with money and decisions, how she shows love or care, what she wants from her own life beyond the marriage, how she is with his family or friends, or what kind of faith or values she holds. Each question should tap a distinct aspect of character, lifestyle, or relationship-avoid vague or overlapping themes.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete and vivid-specific types of women or ways of being, not scales (never 'Very important' or 'Agree/Disagree'). Options should differ clearly: e.g. one might be more traditional, one more independent, one more emotionally expressive, one more reserved or pragmatic. Use short sentences or phrases that sound like real people and real choices (e.g. 'She pushes me to go for it and handles the home front' vs 'She wants us to decide everything together' vs 'She has her own hustle and expects me to support it'). No textbook or generic wording-explore the full range of what men might actually want or recognise in a wife.",

    'attachment_style': "You are a psychologist familiar with attachment theory (Bowlby, Ainsworth). Create an assessment to help someone understand their attachment style in close relationships. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct situations that reveal attachment-e.g. when a partner or close person is distant or busy, when someone wants more closeness than I do, when I'm stressed and need support, when there's conflict or a rupture, when I'm left uncertain about where we stand, when someone depends on me heavily, early in a new relationship, after a disagreement, or when I feel rejected or overlooked. Each question should tap a different scenario (closeness, distance, conflict, need for support, giving support, trust, separation, reconnection) so the full range of attachment behaviours is explored.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete and situational-specific thoughts, feelings, or behaviours people actually have-not scales (never 'Strongly agree' or 'Rarely/Often'). Options should reflect different attachment tendencies: e.g. one might sound secure (comfortable with closeness and space, able to ask for support), one anxious (seek reassurance, worry about abandonment, cling or protest), one avoidant (pull away, minimise need for others, prefer self-reliance), one fearful or mixed (want closeness but also fear it, send mixed signals). Use short sentences that sound like real life (e.g. 'I give them space and focus on my own things' vs 'I check in a lot to make sure we're okay' vs 'I feel relieved when they're busy so I don't have to depend on them'). No textbook labels in the options-describe the behaviour or feeling, not the style name.",

    'what_drives_me': "You are creating an assessment to help someone understand what drives them to pursue goals, projects, or endeavours. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Explore very different situations and angles, e.g. when I start something new, when things get hard or boring, when others doubt me or my idea, when I have to choose between two pursuits, what kind of goals I set (big vs small, safe vs risky), what makes me feel something is worth it, when I lose motivation and why, what reward I care about most (recognition, money, mastery, impact, freedom), why I have quit things in the past, what gets me out of bed for a project, or how I react when I fail. Each question should tap a distinct aspect of drive and motivation (intrinsic vs extrinsic, achievement, proving oneself, curiosity, purpose, fear of failure, recognition, autonomy, legacy).\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete and situational, not scales (never 'Strongly agree' or 'Very important'). Options should differ clearly and reflect different drivers: e.g. one might sound internally driven (curiosity, mastery, meaning), one externally driven (recognition, money, status), one avoidance-driven (proving others wrong, not wanting to regret), one mixed or context-dependent. Use short sentences that sound like real life (e.g. 'I need to see progress or I lose steam' vs 'I keep going even when no one is watching' vs 'I want people to know I did it' vs 'I do it so I don't feel I wasted my chance'). No textbook labels; describe the thought, feeling, or behaviour.",

    'eq_test': "You are a psychologist familiar with emotional intelligence research (Goleman, Salovey & Mayer). Create an assessment to help someone understand their emotional intelligence. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover the core domains of emotional intelligence across distinct real-life situations-e.g. noticing my own emotions as they arise, managing a strong emotion before it takes over, reading someone else's mood without them saying anything, handling a colleague's frustration or criticism, staying calm under pressure or a tight deadline, noticing when I've upset someone, recognising my own triggers before I react, and adjusting how I communicate depending on who I'm talking to. Each question should tap a different domain-self-awareness, self-regulation, empathy, motivation, or social skill-so the full model is covered, not just one facet repeated.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete, situational things someone actually thinks, feels, or does-not scales (never 'Strongly agree' or 'Rarely/Sometimes/Often'). Options should reflect a real range: one high-EI response (aware, regulated, empathetic), one reactive or unaware response, one avoidant or shut-down response, one mixed or context-dependent response. Use short sentences that sound like real life (e.g. 'I notice the tightness in my chest before I say anything' vs 'I don't realise I'm annoyed until I've already snapped' vs 'I push the feeling down and carry on'). No textbook labels in the options-describe the behaviour or feeling, not the EI component name.",

    'emotional_triggers': "You are a psychologist familiar with trauma-informed and nervous-system-based approaches to emotional reactivity (fight, flight, freeze, fawn). Create an assessment to help someone identify their personal emotional triggers and default reaction patterns. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct trigger contexts-e.g. being criticized in front of others, feeling ignored or dismissed, being rushed or put on the spot, sensing someone is disappointed in me, being blamed for something, feeling controlled or micromanaged, being compared to someone else, and conflict with someone close to me. Each question should surface a different kind of trigger (rejection, control, injustice, abandonment, humiliation, being unseen) so the full range of personal triggers is explored, not one theme repeated.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete, specific reactions people actually have in the moment-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should map to different nervous-system responses: one fight-like (get defensive, argue back, get sharp or irritable), one flight-like (want to leave, change the subject, physically distance), one freeze-like (go blank, shut down, say nothing), one fawn-like (over-apologise, agree just to smooth things over, take the blame to end it). Use short, real-life sentences (e.g. 'I go quiet and can't think of what to say' vs 'I feel the urge to defend myself immediately' vs 'I say sorry even when I don't think I did anything wrong'). No textbook labels-describe the reaction itself.",

    'locus_of_control': "You are a psychologist familiar with locus of control theory (Rotter). Create an assessment to help someone understand whether they hold a more internal or external locus of control-whether their sense of worth, mood, and direction come from within themselves or depend on outside people, opinions, and outcomes. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct situations-e.g. when something goes wrong at work or in a project, when I get praised or criticized, when I don't get a result I wanted, when other people disagree with my choices, when I compare my progress to others, when something good happens to me, how I explain my past setbacks, and what determines whether I feel good about myself on a given day. Each question should reveal a different facet of where someone locates responsibility and validation-inside themselves or in outside circumstances/people.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete, situational responses-not scales (never 'Strongly agree' or 'Always/Never'). Options should reflect a real range: one strongly internal (takes ownership, doesn't need outside validation, self-referencing), one strongly external (attributes things to luck/others/circumstances, needs others' approval to feel okay), one mixed, one avoidant/resigned (feels it's out of their hands either way). Use short, real-life sentences (e.g. 'I look at what I could have done differently' vs 'I figure it just wasn't meant to work out' vs 'I need someone to tell me I did well before I actually believe it'). No textbook labels-describe the thought or feeling.",

    'self_compassion': "You are a psychologist familiar with self-compassion research (Kristin Neff: self-kindness vs self-judgment, common humanity vs isolation, mindfulness vs over-identification). Create an assessment to help someone understand how self-compassionate they are. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct moments of struggle-e.g. when I make a mistake at work, when I fail at something I cared about, when I'm going through a hard time emotionally, when I notice a flaw in myself, when I'm physically unwell or exhausted, when I compare myself to people who seem to have it together, when I let someone down, and how I talk to myself in my head during a hard week. Each question should reveal a different facet-self-kindness vs self-criticism, feeling alone in struggle vs recognising it's part of being human, getting swept up in the feeling vs holding it with perspective.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete, real inner responses-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect a real range: one self-compassionate (kind, understanding, keeps perspective), one harshly self-critical, one isolating ('no one else struggles like this', shame-based), one that swings into over-identifying with the feeling (spirals, can't get distance from it). Use short, real-life sentences (e.g. 'I tell myself everyone messes up sometimes' vs 'I replay it and call myself stupid' vs 'I feel like I'm the only one who can't get this right'). No textbook labels-describe the inner voice or feeling.",

    'inner_critic': "You are a psychologist familiar with cognitive-behavioral approaches to self-talk and inner dialogue. Create an assessment to help someone understand the tone and content of their internal voice-whether it functions more like a harsh inner critic or a supportive inner coach. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct moments where inner dialogue shows up-e.g. right after I make a visible mistake, before I attempt something I'm unsure about, when I look in the mirror or see a photo of myself, when I'm falling behind on something I set out to do, when I receive feedback, when I'm comparing myself to someone more successful, when I'm alone with my thoughts at night, and how I'd describe the voice in my head on an average day. Each question should surface a different moment where the inner critic or coach tends to speak up.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that sound like actual internal sentences or reactions-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect a real range: one harsh inner-critic voice (attacking, contemptuous, uses 'always/never'), one inner-coach voice (firm but kind, focused on next steps), one anxious/catastrophizing voice, one flat or dismissive/numb voice. Use short, real inner-monologue-style sentences (e.g. 'Of course you messed this up, you always do' vs 'Okay, that didn't go well-what can I adjust?' vs 'I just don't think about it, I move on'). No textbook labels-write it as the actual internal sentence or feeling.",

    'core_wounds': "You are a psychologist familiar with schema therapy and core-belief work (the idea that early experiences form beliefs like 'I'm not enough', 'I have to earn love', 'It's not safe to need anyone', 'I have to be perfect to be accepted'). Create an assessment to help someone surface their core wounds and limiting beliefs about themselves. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct situations that reveal underlying beliefs-e.g. what I assume when someone doesn't reply to a message, what goes through my mind before I ask for help, what I believe will happen if I show my real feelings to someone, what I think I have to do to be loved or accepted, how I explain it to myself when something good happens to me, what I fear people would think if they really knew me, how I feel about resting or not being productive, and what I believe happens if I fail at something important. Each question should tap a different common core wound (not enough, unlovable, unsafe to need others, must be perfect, must earn worth, invisible/unseen).\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete beliefs or gut reactions-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect different underlying beliefs: e.g. one reflecting 'not enough'/inadequacy, one reflecting fear of being unlovable or abandoned, one reflecting a need to earn worth through achievement or being useful, one more secure/neutral. Use short, real first-thought sentences (e.g. 'I assume I did something wrong' vs 'I figure they're just busy' vs 'I feel like I have to prove I'm worth their time'). No textbook labels-write the actual thought or assumption.",

    'cognitive_distortions': "You are a psychologist familiar with cognitive behavioral therapy (CBT) and common cognitive distortions (catastrophizing, black-and-white thinking, mind-reading, personalization, overgeneralization, should-statements, emotional reasoning, filtering). Create an assessment to help someone identify which cognitive distortions they fall into most. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct situations where distorted thinking shows up-e.g. when one thing goes wrong in an otherwise good day, when someone takes a while to reply to me, when I make a small mistake in front of others, when I imagine a future event that matters to me, when someone is quiet or short with me, when I don't meet a standard I set for myself, when I think about a past decision that didn't work out, and how I interpret a mixed piece of feedback. Each question should reveal a different distortion so the range is covered, not one theme repeated.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete thoughts people actually have-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should map to different distortions: one catastrophizing ('this is going to ruin everything'), one black-and-white ('if it's not perfect it's worthless'), one mind-reading/personalizing ('they must be upset with me'), one balanced/realistic thought. Use short, real-thought sentences (e.g. 'This one mistake means the whole thing is ruined' vs 'They're probably just having a busy day' vs 'One bad moment doesn't erase the good ones'). No textbook labels-write the actual thought.",

    'defense_mechanisms': "You are a psychologist familiar with psychodynamic defense mechanisms (denial, projection, rationalization, displacement, intellectualization, repression, sublimation, reaction formation). Create an assessment to help someone understand which defense mechanisms they default to under stress or discomfort. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct stressful moments-e.g. when someone points out a flaw in something I did, when I feel a difficult emotion I'd rather not feel, when I'm frustrated with someone but can't say it directly to them, when I'm asked to talk about something uncomfortable, when I'm caught doing something I shouldn't have, when I notice a trait in someone else that bothers me a lot, when things feel emotionally overwhelming, and how I typically explain away a personal failure. Each question should surface a different defense mechanism.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete behaviours or thoughts-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should map to different defenses: one denial-like (dismisses/minimises it happened or matters), one projection-like (attributes their own feeling/flaw to someone else), one rationalization/intellectualization-like (explains it away logically, over-analyses instead of feeling it), one more direct/aware response. Use short, real-life sentences (e.g. 'I explain it away with a good reason and move on' vs 'I get irritated that they're being so sensitive about it' vs 'I just say it wasn't a big deal, even if it was'). No textbook labels in the options-describe the behaviour or thought.",

    'stoic_mindset': "You are a psychologist and philosophy teacher familiar with Stoic philosophy (Epictetus's dichotomy of control, Marcus Aurelius, Seneca-focusing on what is and isn't within one's control, and equanimity in the face of adversity). Create an assessment to help someone understand how 'Stoic' their actual habits of mind are. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct situations that test Stoic principles-e.g. when a plan falls apart due to something outside my control, when someone else's opinion of me is unfair, when I'm stuck in traffic or a delay, when I don't get a result I worked hard for, when someone insults or provokes me, when I'm waiting on something I can't influence, how I think about things that could go wrong before they happen, and how I respond to physical discomfort or inconvenience. Each question should reveal whether the person's focus goes to what they can control (their judgment, effort, response) or what they can't (outcomes, others, circumstance).\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete reactions-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect a real range: one Stoic/equanimous response (accepts what can't be controlled, focuses on response/effort), one reactive/emotionally hijacked response, one avoidant/resigned response, one that fights reality (resists, complains, insists it shouldn't be happening). Use short, real-life sentences (e.g. 'I remind myself this part isn't up to me and focus on what I can still do' vs 'I get worked up about it even though I can't change it' vs 'I just shut down and stop trying'). No textbook labels-describe the actual reaction.",

    'shame_resilience': "You are a psychologist familiar with shame and vulnerability research (Brene Brown's work on shame resilience, and common shame responses: moving away/withdrawing, moving toward/people-pleasing, moving against/attacking). Create an assessment to help someone understand their relationship with shame and how resilient they are to it. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct shame-triggering moments-e.g. when I'm caught in a mistake in front of people I respect, when I feel like I don't measure up to a standard I care about, when something personal about me is exposed or judged, when I disappoint someone I look up to, when I compare my life stage to peers, when I'm called out for something I did wrong, when I feel like an impostor in a room, and how I generally handle feeling embarrassed. Each question should reveal a different shame response and how much the person can stay open and grounded versus collapsing, attacking, or hiding.\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete reactions-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect a real range: one shame-resilient response (owns it, stays connected, doesn't collapse into 'I am bad'), one withdrawing/hiding response, one people-pleasing/over-apologising response, one attacking/defensive response (blame others, get sharp). Use short, real-life sentences (e.g. 'I feel it, admit it, and move forward without making it mean I'm a bad person' vs 'I want to disappear and avoid everyone for a while' vs 'I get defensive and point out what wasn't my fault'). No textbook labels-describe the actual reaction.",

    'boundaries': "You are a psychologist familiar with boundaries and people-pleasing patterns. Create an assessment to help someone understand how well they set and maintain personal boundaries. Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct boundary situations-e.g. when someone asks me for a favor I don't have time for, when someone crosses a line with me (time, money, respect), when I disagree with someone close to me, when I need to say no to a request, when someone is upset with a decision I made for myself, when I'm asked to take on more than feels fair at work, when I want alone time but someone wants my attention, and how I feel after I've said yes to something I didn't want to do. Each question should reveal a different aspect of boundary-setting (saying no, tolerating others' disappointment, protecting time/energy, speaking up when crossed).\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete behaviours or thoughts-not scales (never 'Strongly agree' or 'Often/Rarely'). Options should reflect a real range: one clear/healthy boundary response (says no or states the line calmly, without over-explaining), one people-pleasing response (agrees despite resentment, over-explains or over-apologises), one avoidant response (dodges the conversation, goes along with it quietly), one over-firm/defensive response (reacts harshly to protect the line). Use short, real-life sentences (e.g. 'I say I can't this time, without a long explanation' vs 'I say yes and then feel resentful about it later' vs 'I avoid answering and hope it goes away'). No textbook labels-describe the actual behaviour or thought.",

    'values_clarification': "You are a psychologist familiar with values-clarification work (as used in ACT-Acceptance and Commitment Therapy). Create an assessment to help someone distinguish what they genuinely value from what they feel they're supposed to value (family/social expectation, status, obligation). Generate exactly 8 multiple-choice questions. Each question must have exactly 4 options.\n\nDIVERGENT QUESTIONS: Cover distinct life domains-e.g. what I'd actually spend a completely free weekend doing if no one would know or judge, what kind of achievement genuinely moves me versus just looks good, what I'd feel proud of on my own even if no one noticed, how I decide what career or project path to pursue, what kind of person I want to be known as by the people closest to me, what I'd protect first if I had to simplify my life, what I actually enjoy talking about versus what I talk about to fit in, and what I'd regret not doing if my life were much shorter than expected. Each question should reveal whether the person's choices are self-referenced (genuine values) or other-referenced (social expectation, obligation, image).\n\nDIVERGENT, REALISTIC OPTIONS: For each question give 4 options that are concrete, specific choices-not scales (never 'Strongly agree' or 'Very important'). Options should reflect a real range: one clearly self-referenced/intrinsic value (connection, creativity, mastery, integrity, adventure), one status/image-driven value, one obligation/duty-driven value (because it's expected of me), one avoidance-driven choice (whatever is safest or causes least friction). Use short, real-life sentences (e.g. 'I'd spend it building or learning something just because it interests me' vs 'I'd want to have something to show for it so people are impressed' vs 'I'd do what's expected so no one is disappointed in me'). No textbook labels-describe the actual choice or feeling.",
}

BUILTIN_ANALYSIS_INSTRUCTIONS: dict[str, str] = {
    'self_esteem': "You are a supportive psychologist. Based on the following self-esteem assessment questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Address: strengths in their self-view, areas that may suggest lower self-esteem (e.g. self-criticism, comparison, difficulty asserting needs), and one or two gentle, actionable suggestions. Be warm and non-judgmental. Write in first person as if the user is speaking about themselves: use 'I', 'my', 'me' throughout (e.g. 'I tend to...', 'My self-view...').",

    'kind_of_wife': "You are a thoughtful advisor. Based on the following questions and the user's answers about the kind of wife he is looking for, write a concise, personalized portrait (2–4 short paragraphs). Describe: the kind of wife that best fits his answers-her likely traits, what she tends to value, how she might show up in a relationship and in daily life, and how she would complement him. Be specific and grounded in his actual choices; avoid generic flattery. You may briefly note patterns in his choices (e.g. he leans toward someone independent, or someone who prioritises family harmony) and what that might mean for him. Write in first person when referring to the user: use 'I', 'my', 'me' (e.g. 'I'm looking for someone who...', 'My answers suggest...'). When describing the kind of wife use 'she'/'her'. Tone: warm, insightful, and realistic.",

    'attachment_style': "You are a psychologist familiar with attachment theory. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe their likely attachment style or mix of tendencies (secure, anxious-preoccupied, dismissive-avoidant, fearful-avoidant) in plain language, grounded in their actual answers. Explain what that might mean for their relationships-how they might show up, what they might find easy or hard, and one or two gentle suggestions if relevant (e.g. naming needs, tolerating closeness). Be warm and non-pathologising; attachment styles are normal adaptations. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to...', 'My pattern might be...', 'In my relationships...').",

    'what_drives_me': "You are a thoughtful advisor. Based on the following questions and the user's answers about what drives them to pursue goals or endeavours, write a concise, personalized analysis (2–4 short paragraphs). Describe what seems to drive them (e.g. intrinsic motivation, recognition, mastery, impact, proving oneself, avoiding regret, curiosity, purpose, autonomy) in plain language, grounded in their actual answers. Explain what that might mean for how they pursue things, when they are likely to stay motivated or lose steam, and one or two gentle suggestions if relevant (e.g. aligning projects with their drivers, naming what they need). Be warm and insightful. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I am driven by...', 'What tends to keep me going...', 'In my pursuits...').",

    'eq_test': "You are a psychologist familiar with emotional intelligence research. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Address: which domains of emotional intelligence (self-awareness, self-regulation, empathy, motivation, social skill) seem strongest, which seem like growth areas, and one or two concrete, practical suggestions for building the weaker areas (e.g. naming the emotion in the moment, a pause-before-reacting practice, checking in on how others might be feeling). Be warm, non-judgmental, and practical rather than clinical. Write in first person as if the user is speaking about themselves: use 'I', 'my', 'me' throughout (e.g. 'I tend to...', 'My strongest area seems to be...').",

    'emotional_triggers': "You are a psychologist familiar with trauma-informed nervous-system responses (fight, flight, freeze, fawn). Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Identify: the kinds of situations that seem to trigger them most (e.g. rejection, control, injustice, being unseen), their dominant reactivity pattern(s) (fight, flight, freeze, fawn, or a mix), and one or two gentle, practical suggestions for noticing the trigger earlier and responding rather than reacting (e.g. naming the trigger in the moment, a grounding technique, pausing before responding). Be warm and non-pathologising-these are normal survival patterns, not flaws. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to get triggered by...', 'My default reaction is...').",

    'locus_of_control': "You are a psychologist familiar with locus of control theory. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe whether their answers suggest a more internal or external locus of control (or a mix, and in which situations it shifts), what that means for how dependent their confidence and mood are on outside people or outcomes, and one or two gentle, practical suggestions for building a more internally-anchored sense of worth (e.g. separating self-worth from results, noticing when they're seeking outside approval). Be warm and non-judgmental-this is about awareness, not a verdict. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to rely on...', 'My sense of okay-ness often depends on...').",

    'self_compassion': "You are a psychologist familiar with self-compassion research (Kristin Neff's model). Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe how self-compassionate their answers suggest they are, which component seems weakest (self-kindness, common humanity, or mindfulness), what that pattern likely costs them day to day, and one or two gentle, practical suggestions for building more self-compassion (e.g. a phrase to use when they mess up, noticing the inner critic's voice as separate from fact). Be warm, non-judgmental, and encouraging-the point is awareness, not more self-criticism about being self-critical. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'When I struggle, I tend to...', 'My inner voice often...').",

    'inner_critic': "You are a psychologist familiar with self-talk and inner-dialogue research. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe the dominant tone of their inner voice (harsh critic, encouraging coach, anxious, numb/dismissive, or a mix and when each shows up), what that inner dialogue likely costs or gives them, and one or two concrete, practical suggestions for shifting a harsh inner critic toward a firmer-but-kinder inner coach (e.g. a specific reframe, noticing the voice and naming it as separate from truth). Be warm and non-judgmental. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'The voice in my head tends to...', 'When I mess up, I usually tell myself...').",

    'core_wounds': "You are a psychologist familiar with core-belief and schema-based approaches. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Gently name the core belief(s) or wound(s) their answers point to (e.g. a fear of not being enough, a belief that worth has to be earned, a fear that needing others isn't safe), where this might be showing up in their life now (relationships, work, self-talk), and one or two gentle, practical suggestions for starting to question or loosen the belief (e.g. noticing when the belief is speaking versus what's actually true, a small counter-experiment). Be especially warm, careful, and non-pathologising here-this territory can feel vulnerable; frame it as insight, not diagnosis. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'Somewhere along the way I came to believe...', 'This shows up for me when...').",

    'cognitive_distortions': "You are a psychologist familiar with CBT and cognitive distortions. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Name the distortion(s) that show up most in their answers (e.g. catastrophizing, black-and-white thinking, mind-reading, personalization), give a concrete example from their own answers of how it plays out, and one or two practical CBT-style suggestions for catching and reframing the thought in the moment (e.g. asking 'what's the evidence', naming the distortion when it shows up). Be warm, practical, and non-judgmental-everyone has some of these; the point is noticing them. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to jump to...', 'My mind often tells me...').",

    'defense_mechanisms': "You are a psychologist familiar with psychodynamic defense mechanisms. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Identify the defense mechanism(s) that show up most (e.g. denial, projection, rationalization, intellectualization, displacement), describe what they might be protecting the person from feeling, and one or two gentle, practical suggestions for noticing the defense in the moment and sitting with the underlying feeling instead (e.g. pausing to name the emotion before explaining it away). Be warm and non-pathologising-defenses are normal and protective, not character flaws. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'When something's hard to face, I tend to...', 'I often protect myself by...').",

    'stoic_mindset': "You are a psychologist and philosophy teacher familiar with Stoic philosophy. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe how well their answers suggest they separate what's in their control from what isn't, where they tend to get emotionally hijacked by things outside their control, and one or two concrete, practical Stoic-inspired suggestions (e.g. the dichotomy-of-control pause, reframing an obstacle as material to work with, premeditatio malorum in small doses). Be warm, grounded, and practical rather than preachy. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to get pulled into...', 'What helps me stay grounded is...').",

    'shame_resilience': "You are a psychologist familiar with shame and vulnerability research. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe their dominant shame response pattern(s) (withdrawing, people-pleasing, attacking, or staying grounded/resilient, and in which situations), what this pattern likely costs them, and one or two gentle, practical suggestions for building more shame resilience (e.g. separating 'I did a bad thing' from 'I am bad', naming the feeling to someone safe). Be especially warm and non-judgmental-shame is universal, and the goal is awareness and self-kindness, not more shame about the pattern. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'When I feel exposed, I tend to...', 'My instinct in that moment is...').",

    'boundaries': "You are a psychologist familiar with boundaries and people-pleasing patterns. Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe how their answers suggest they handle boundaries (e.g. tend to over-give, avoid conflict, hold firm lines, or a mix depending on who's asking), what this costs them (resentment, burnout, being taken for granted), and one or two concrete, practical suggestions for setting boundaries more clearly (e.g. a simple no-script, noticing resentment as a signal a boundary was crossed). Be warm and non-judgmental-this is about patterns, not a character flaw. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'I tend to say yes even when...', 'I find it hard to...').",

    'values_clarification': "You are a psychologist familiar with values-clarification work (ACT-based). Based on the following questions and the user's answers, write a concise, personalized analysis (2–4 short paragraphs). Describe what their answers suggest they genuinely value (e.g. connection, mastery, creativity, integrity, freedom), where their choices seem to be driven instead by social expectation, obligation, or image, and one or two gentle, practical suggestions for living more in line with their real values (e.g. one small values-aligned action this week, noticing when a choice is 'should' versus 'want'). Be warm and encouraging. Write in first person as if the user is speaking: use 'I', 'my', 'me' throughout (e.g. 'What I actually seem to value is...', 'I notice I sometimes choose things because...').",
}

BUILTIN_ASSESSMENT_META: list[dict] = [
    {"test_id": "self_esteem", "title": 'Self Esteem Test', "tagline": 'Understand my self-worth and areas to grow.', "sort_order": 0},
    {"test_id": "kind_of_wife", "title": "Kind of Wife I'm Looking For", "tagline": "Discover the kind of wife that fits me, traits, values, and how she'd complement my life.", "sort_order": 1},
    {"test_id": "attachment_style", "title": 'My Attachment Style', "tagline": 'Understand my attachment style in relationships (secure, anxious, avoidant, or mixed) and what it means for me.', "sort_order": 2},
    {"test_id": "what_drives_me", "title": 'What Drives Me to Pursue Something', "tagline": 'Discover what really drives me to pursue goals, projects, and endeavours and what it means for how I show up.', "sort_order": 3},
    {"test_id": "eq_test", "title": 'Emotional Intelligence (EQ) Test', "tagline": 'Understand my emotional intelligence - self-awareness, self-regulation, empathy, and social skill.', "sort_order": 4},
    {"test_id": "emotional_triggers", "title": 'Emotional Triggers & Reactivity Test', "tagline": 'Discover what actually triggers me and how I tend to react - fight, flight, freeze, or fawn.', "sort_order": 5},
    {"test_id": "locus_of_control", "title": 'Locus of Control Test', "tagline": "Discover whether my sense of okay-ness comes from within me or depends on outside people and outcomes.", "sort_order": 6},
    {"test_id": "self_compassion", "title": 'Self-Compassion Test', "tagline": 'Understand how kindly (or harshly) I treat myself when I struggle or fail.', "sort_order": 7},
    {"test_id": "inner_critic", "title": 'Inner Critic vs Inner Coach', "tagline": 'Discover the actual tone and content of my self-talk, and whether it builds me up or tears me down.', "sort_order": 8},
    {"test_id": "core_wounds", "title": 'Core Wounds & Limiting Beliefs', "tagline": "Find the early beliefs about myself that quietly shape how I think, act, and hold back.", "sort_order": 9},
    {"test_id": "cognitive_distortions", "title": 'Cognitive Distortions Test', "tagline": 'Spot the specific thinking traps that quietly distort how I see myself and situations.', "sort_order": 10},
    {"test_id": "defense_mechanisms", "title": 'Defense Mechanisms Test', "tagline": 'Discover which psychological defenses I default to under stress, criticism, or discomfort.', "sort_order": 11},
    {"test_id": "stoic_mindset", "title": 'Stoic Mindset Test', "tagline": "Understand how well I separate what's in my control from what isn't, and how I respond to adversity.", "sort_order": 12},
    {"test_id": "shame_resilience", "title": 'Shame Resilience Test', "tagline": 'Understand how I respond to shame - whether I numb, deflect, attack, or stay grounded and open.', "sort_order": 13},
    {"test_id": "boundaries", "title": 'Boundaries Test', "tagline": 'Understand how well I set and hold personal boundaries, and where I tend to over-give or overextend.', "sort_order": 14},
    {"test_id": "values_clarification", "title": 'Values Clarification Test', "tagline": "Discover what I actually value, versus what I think I'm supposed to value, so my identity is anchored in me.", "sort_order": 15},
]

KNOWN_TEST_IDS: tuple[str, ...] = tuple(m['test_id'] for m in BUILTIN_ASSESSMENT_META)
