"""added models for storing prompts

Revision ID: 09249d30435f
Revises: c35af9c50603
Create Date: 2026-04-26 21:54:12.910784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09249d30435f'
down_revision: Union[str, None] = 'c35af9c50603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_discovery_assessments',
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=False),
    sa.Column('questions_instruction_html', sa.Text(), nullable=False),
    sa.Column('analysis_instruction_html', sa.Text(), nullable=False),
    sa.Column('llm_request_body_template', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_discovery_assessments')
    # ### end Alembic commands ###

