"""added refresh rate field to be used during exercises to show stats

Revision ID: 1488a8c4355e
Revises: c8b011c98715
Create Date: 2026-03-23 18:54:06.980740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1488a8c4355e'
down_revision: Union[str, None] = 'c8b011c98715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stats_refresh_interval_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stats_refresh_interval_seconds')
    # ### end Alembic commands ###

