"""added upcoming expense model

Revision ID: 1cfd8203595b
Revises: cf38297d2aa3
Create Date: 2026-02-19 17:40:24.654744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfd8203595b'
down_revision: Union[str, None] = 'cf38297d2aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upcoming_expenses_due_date'), 'upcoming_expenses', ['due_date'], unique=False)
    op.create_index(op.f('ix_upcoming_expenses_id'), 'upcoming_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_upcoming_expenses_user_id'), 'upcoming_expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upcoming_expenses_user_id'), table_name='upcoming_expenses')
    op.drop_index(op.f('ix_upcoming_expenses_id'), table_name='upcoming_expenses')
    op.drop_index(op.f('ix_upcoming_expenses_due_date'), table_name='upcoming_expenses')
    op.drop_table('upcoming_expenses')
    # ### end Alembic commands ###

