"""add daily productive items table

Revision ID: 33fe42bda9cf
Revises: 98b88a266143
Create Date: 2026-09-23 01:07:07.776840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fe42bda9cf'
down_revision: Union[str, None] = '98b88a266143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_productive_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('item_date', sa.Date(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_productive_items_id'), 'daily_productive_items', ['id'], unique=False)
    op.create_index(op.f('ix_daily_productive_items_item_date'), 'daily_productive_items', ['item_date'], unique=False)
    op.create_index(op.f('ix_daily_productive_items_user_id'), 'daily_productive_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_productive_items_user_id'), table_name='daily_productive_items')
    op.drop_index(op.f('ix_daily_productive_items_item_date'), table_name='daily_productive_items')
    op.drop_index(op.f('ix_daily_productive_items_id'), table_name='daily_productive_items')
    op.drop_table('daily_productive_items')
    # ### end Alembic commands ###

