"""add youtube channel management tables

Revision ID: 5208ce42f675
Revises: b0e892ed7c11
Create Date: 2026-08-22 19:49:06.117098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5208ce42f675'
down_revision: Union[str, None] = 'b0e892ed7c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_email', name='uq_youtube_accounts_user_email')
    )
    op.create_index(op.f('ix_youtube_accounts_id'), 'youtube_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_accounts_user_id'), 'youtube_accounts', ['user_id'], unique=False)
    op.create_table('youtube_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('is_monetized', sa.Boolean(), nullable=False),
    sa.Column('estimated_rpm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['youtube_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id', name='uq_youtube_channels_channel_id')
    )
    op.create_index(op.f('ix_youtube_channels_account_id'), 'youtube_channels', ['account_id'], unique=False)
    op.create_index(op.f('ix_youtube_channels_id'), 'youtube_channels', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_channels_youtube_channel_id'), 'youtube_channels', ['youtube_channel_id'], unique=False)
    op.create_table('youtube_channel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('watch_time_hours', sa.Float(), nullable=True),
    sa.Column('month_to_date_views', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_channel_stats_channel_id'), 'youtube_channel_stats', ['channel_id'], unique=False)
    op.create_index(op.f('ix_youtube_channel_stats_id'), 'youtube_channel_stats', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_channel_stats_synced_at'), 'youtube_channel_stats', ['synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_channel_stats_synced_at'), table_name='youtube_channel_stats')
    op.drop_index(op.f('ix_youtube_channel_stats_id'), table_name='youtube_channel_stats')
    op.drop_index(op.f('ix_youtube_channel_stats_channel_id'), table_name='youtube_channel_stats')
    op.drop_table('youtube_channel_stats')
    op.drop_index(op.f('ix_youtube_channels_youtube_channel_id'), table_name='youtube_channels')
    op.drop_index(op.f('ix_youtube_channels_id'), table_name='youtube_channels')
    op.drop_index(op.f('ix_youtube_channels_account_id'), table_name='youtube_channels')
    op.drop_table('youtube_channels')
    op.drop_index(op.f('ix_youtube_accounts_user_id'), table_name='youtube_accounts')
    op.drop_index(op.f('ix_youtube_accounts_id'), table_name='youtube_accounts')
    op.drop_table('youtube_accounts')
    # ### end Alembic commands ###

