"""added models for category and items for pending work

Revision ID: 54e4a77a9465
Revises: 26aef2bd83c6
Create Date: 2026-04-11 08:29:12.318883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e4a77a9465'
down_revision: Union[str, None] = '26aef2bd83c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_work_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_pending_work_categories_user_client_id')
    )
    op.create_index(op.f('ix_pending_work_categories_id'), 'pending_work_categories', ['id'], unique=False)
    op.create_index(op.f('ix_pending_work_categories_user_id'), 'pending_work_categories', ['user_id'], unique=False)
    op.create_table('pending_work_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['pending_work_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_pending_work_items_user_client_id')
    )
    op.create_index(op.f('ix_pending_work_items_category_id'), 'pending_work_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_pending_work_items_id'), 'pending_work_items', ['id'], unique=False)
    op.create_index(op.f('ix_pending_work_items_user_id'), 'pending_work_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_work_items_user_id'), table_name='pending_work_items')
    op.drop_index(op.f('ix_pending_work_items_id'), table_name='pending_work_items')
    op.drop_index(op.f('ix_pending_work_items_category_id'), table_name='pending_work_items')
    op.drop_table('pending_work_items')
    op.drop_index(op.f('ix_pending_work_categories_user_id'), table_name='pending_work_categories')
    op.drop_index(op.f('ix_pending_work_categories_id'), table_name='pending_work_categories')
    op.drop_table('pending_work_categories')
    # ### end Alembic commands ###

