"""added models for storing api keys

Revision ID: 690ce2ba5a56
Revises: cdf0c70710bb
Create Date: 2026-04-26 18:10:38.841490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690ce2ba5a56'
down_revision: Union[str, None] = 'cdf0c70710bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_user_api_providers_user_normalized_name')
    )
    op.create_index(op.f('ix_user_api_providers_id'), 'user_api_providers', ['id'], unique=False)
    op.create_index(op.f('ix_user_api_providers_normalized_name'), 'user_api_providers', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_user_api_providers_user_id'), 'user_api_providers', ['user_id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_secret', sa.Text(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_api_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_api_keys_provider_id'), 'user_api_keys', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_provider_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_user_api_providers_user_id'), table_name='user_api_providers')
    op.drop_index(op.f('ix_user_api_providers_normalized_name'), table_name='user_api_providers')
    op.drop_index(op.f('ix_user_api_providers_id'), table_name='user_api_providers')
    op.drop_table('user_api_providers')
    # ### end Alembic commands ###

