"""added running met value to enable adjustment of calories and fat loss computed

Revision ID: 7055ff5d8612
Revises: 9aaa50f90a9e
Create Date: 2026-03-24 11:02:14.783584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7055ff5d8612'
down_revision: Union[str, None] = '9aaa50f90a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('running_met', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'running_met')
    # ### end Alembic commands ###

