"""replace_user_api_provider_tables_with_user_llm_api_keys

Revision ID: 7abd2e311485
Revises: 09249d30435f
Create Date: 2026-04-26 23:29:38.992983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7abd2e311485'
down_revision: Union[str, None] = '09249d30435f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_llm_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_secret', sa.Text(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_slug', 'name', name='uq_user_llm_api_keys_user_provider_name')
    )
    op.create_index(op.f('ix_user_llm_api_keys_id'), 'user_llm_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_llm_api_keys_provider_slug'), 'user_llm_api_keys', ['provider_slug'], unique=False)
    op.create_index(op.f('ix_user_llm_api_keys_user_id'), 'user_llm_api_keys', ['user_id'], unique=False)
    op.drop_index('ix_user_api_provider_models_id', table_name='user_api_provider_models')
    op.drop_index('ix_user_api_provider_models_provider_id', table_name='user_api_provider_models')
    op.drop_table('user_api_provider_models')
    op.drop_index('ix_user_api_keys_id', table_name='user_api_keys')
    op.drop_index('ix_user_api_keys_provider_id', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index('ix_user_api_providers_id', table_name='user_api_providers')
    op.drop_index('ix_user_api_providers_normalized_name', table_name='user_api_providers')
    op.drop_index('ix_user_api_providers_user_id', table_name='user_api_providers')
    op.drop_table('user_api_providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_providers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_api_providers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('normalized_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_api_providers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_api_providers_pkey'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_user_api_providers_user_normalized_name'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_api_providers_user_id', 'user_api_providers', ['user_id'], unique=False)
    op.create_index('ix_user_api_providers_normalized_name', 'user_api_providers', ['normalized_name'], unique=False)
    op.create_index('ix_user_api_providers_id', 'user_api_providers', ['id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('key_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_api_providers.id'], name='user_api_keys_provider_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_api_keys_pkey')
    )
    op.create_index('ix_user_api_keys_provider_id', 'user_api_keys', ['provider_id'], unique=False)
    op.create_index('ix_user_api_keys_id', 'user_api_keys', ['id'], unique=False)
    op.create_table('user_api_provider_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_api_providers.id'], name='user_api_provider_models_provider_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_api_provider_models_pkey'),
    sa.UniqueConstraint('provider_id', 'slug', name='uq_user_api_provider_models_provider_slug')
    )
    op.create_index('ix_user_api_provider_models_provider_id', 'user_api_provider_models', ['provider_id'], unique=False)
    op.create_index('ix_user_api_provider_models_id', 'user_api_provider_models', ['id'], unique=False)
    op.drop_index(op.f('ix_user_llm_api_keys_user_id'), table_name='user_llm_api_keys')
    op.drop_index(op.f('ix_user_llm_api_keys_provider_slug'), table_name='user_llm_api_keys')
    op.drop_index(op.f('ix_user_llm_api_keys_id'), table_name='user_llm_api_keys')
    op.drop_table('user_llm_api_keys')
    # ### end Alembic commands ###

