"""add position to daily productive items

Revision ID: 85d9e2a9090a
Revises: 33fe42bda9cf
Create Date: 2026-09-23 22:10:02.826214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d9e2a9090a'
down_revision: Union[str, None] = '33fe42bda9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('daily_productive_items', sa.Column('position', sa.Integer(), nullable=True))
    op.execute('UPDATE daily_productive_items SET position = id')
    op.alter_column('daily_productive_items', 'position', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_productive_items', 'position')
    # ### end Alembic commands ###

