"""add azw books

Revision ID: 88e669cfa067
Revises: adea1063047a
Create Date: 2026-07-31 10:18:42.402352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e669cfa067'
down_revision: Union[str, None] = 'adea1063047a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azw_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['reading_authors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azw_books_author_id'), 'azw_books', ['author_id'], unique=False)
    op.create_index(op.f('ix_azw_books_id'), 'azw_books', ['id'], unique=False)
    op.create_index(op.f('ix_azw_books_user_id'), 'azw_books', ['user_id'], unique=False)
    op.create_table('azw_book_categories',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['azw_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['reading_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.create_table('azw_book_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['azw_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azw_book_chapters_book_id'), 'azw_book_chapters', ['book_id'], unique=False)
    op.create_index(op.f('ix_azw_book_chapters_id'), 'azw_book_chapters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_azw_book_chapters_id'), table_name='azw_book_chapters')
    op.drop_index(op.f('ix_azw_book_chapters_book_id'), table_name='azw_book_chapters')
    op.drop_table('azw_book_chapters')
    op.drop_table('azw_book_categories')
    op.drop_index(op.f('ix_azw_books_user_id'), table_name='azw_books')
    op.drop_index(op.f('ix_azw_books_id'), table_name='azw_books')
    op.drop_index(op.f('ix_azw_books_author_id'), table_name='azw_books')
    op.drop_table('azw_books')
    # ### end Alembic commands ###

