"""added time tracking functionality models

Revision ID: 88ecaeca117b
Revises: 8b99983b6437
Create Date: 2026-03-28 15:30:08.393050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ecaeca117b'
down_revision: Union[str, None] = '8b99983b6437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_tracker_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_entry_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=512), nullable=False),
    sa.Column('subject_name', sa.String(length=512), nullable=False),
    sa.Column('parent_goal_id', sa.String(length=512), nullable=True),
    sa.Column('parent_goal_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_entry_id', name='uq_time_tracker_entries_user_client_id')
    )
    op.create_index(op.f('ix_time_tracker_entries_id'), 'time_tracker_entries', ['id'], unique=False)
    op.create_index(op.f('ix_time_tracker_entries_started_at'), 'time_tracker_entries', ['started_at'], unique=False)
    op.create_index(op.f('ix_time_tracker_entries_user_id'), 'time_tracker_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_tracker_entries_user_id'), table_name='time_tracker_entries')
    op.drop_index(op.f('ix_time_tracker_entries_started_at'), table_name='time_tracker_entries')
    op.drop_index(op.f('ix_time_tracker_entries_id'), table_name='time_tracker_entries')
    op.drop_table('time_tracker_entries')
    # ### end Alembic commands ###

