"""added ability to save resumes in the db

Revision ID: 8b99983b6437
Revises: fc746422850f
Create Date: 2026-03-28 00:21:34.893300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b99983b6437'
down_revision: Union[str, None] = 'fc746422850f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_resume_doc_user_external')
    )
    op.create_index(op.f('ix_resume_documents_id'), 'resume_documents', ['id'], unique=False)
    op.create_index(op.f('ix_resume_documents_user_id'), 'resume_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_documents_user_id'), table_name='resume_documents')
    op.drop_index(op.f('ix_resume_documents_id'), table_name='resume_documents')
    op.drop_table('resume_documents')
    # ### end Alembic commands ###

