"""add group_label to youtube_accounts

Revision ID: 98b88a266143
Revises: 5208ce42f675
Create Date: 2026-08-23 00:32:13.649255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b88a266143'
down_revision: Union[str, None] = '5208ce42f675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_accounts', sa.Column('group_label', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_youtube_accounts_group_label'), 'youtube_accounts', ['group_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_accounts_group_label'), table_name='youtube_accounts')
    op.drop_column('youtube_accounts', 'group_label')
    # ### end Alembic commands ###

