"""added is_completed column on the runsession model

Revision ID: 9aaa50f90a9e
Revises: 1488a8c4355e
Create Date: 2026-03-23 20:35:05.863249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa50f90a9e'
down_revision: Union[str, None] = '1488a8c4355e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_sessions', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_sessions', 'is_completed')
    # ### end Alembic commands ###

