"""add investment game save

Revision ID: adea1063047a
Revises: e6d27e8a9ef3
Create Date: 2026-07-26 16:29:12.975462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adea1063047a'
down_revision: Union[str, None] = 'e6d27e8a9ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_saves_id'), 'game_saves', ['id'], unique=False)
    op.create_index(op.f('ix_game_saves_user_id'), 'game_saves', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_saves_user_id'), table_name='game_saves')
    op.drop_index(op.f('ix_game_saves_id'), table_name='game_saves')
    op.drop_table('game_saves')
    # ### end Alembic commands ###

