"""add azw book chapter is_copied

Revision ID: b0e892ed7c11
Revises: 88e669cfa067
Create Date: 2026-07-31 11:22:12.010558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e892ed7c11'
down_revision: Union[str, None] = '88e669cfa067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azw_book_chapters', sa.Column('is_copied', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azw_book_chapters', 'is_copied')
    # ### end Alembic commands ###

