"""added models for tracking book reading

Revision ID: c021e93dc4b6
Revises: d87717e1917e
Create Date: 2026-03-29 00:30:11.831138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c021e93dc4b6'
down_revision: Union[str, None] = 'd87717e1917e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_authors_user_id'), 'reading_authors', ['user_id'], unique=False)
    op.create_table('reading_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_categories_user_id'), 'reading_categories', ['user_id'], unique=False)
    op.create_table('reading_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('shelf', sa.String(length=16), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['reading_authors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_books_author_id'), 'reading_books', ['author_id'], unique=False)
    op.create_index(op.f('ix_reading_books_user_id'), 'reading_books', ['user_id'], unique=False)
    op.create_table('reading_book_categories',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['reading_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['reading_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_book_categories')
    op.drop_index(op.f('ix_reading_books_user_id'), table_name='reading_books')
    op.drop_index(op.f('ix_reading_books_author_id'), table_name='reading_books')
    op.drop_table('reading_books')
    op.drop_index(op.f('ix_reading_categories_user_id'), table_name='reading_categories')
    op.drop_table('reading_categories')
    op.drop_index(op.f('ix_reading_authors_user_id'), table_name='reading_authors')
    op.drop_table('reading_authors')
    # ### end Alembic commands ###

