"""added ability to save models for providers

Revision ID: c35af9c50603
Revises: 690ce2ba5a56
Create Date: 2026-04-26 20:14:35.525457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35af9c50603'
down_revision: Union[str, None] = '690ce2ba5a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_provider_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_api_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'slug', name='uq_user_api_provider_models_provider_slug')
    )
    op.create_index(op.f('ix_user_api_provider_models_id'), 'user_api_provider_models', ['id'], unique=False)
    op.create_index(op.f('ix_user_api_provider_models_provider_id'), 'user_api_provider_models', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_provider_models_provider_id'), table_name='user_api_provider_models')
    op.drop_index(op.f('ix_user_api_provider_models_id'), table_name='user_api_provider_models')
    op.drop_table('user_api_provider_models')
    # ### end Alembic commands ###

