"""added the run sessions table

Revision ID: c8b011c98715
Revises: f6ef931d7442
Create Date: 2026-03-23 18:45:05.777968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b011c98715'
down_revision: Union[str, None] = 'f6ef931d7442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('tick_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fat_equiv_kg', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sessions_id'), 'run_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_run_sessions_user_id'), 'run_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_sessions_user_id'), table_name='run_sessions')
    op.drop_index(op.f('ix_run_sessions_id'), table_name='run_sessions')
    op.drop_table('run_sessions')
    # ### end Alembic commands ###

