"""add shares feasibility feature

Revision ID: cdf0c70710bb
Revises: fda8f097bf7a
Create Date: 2026-04-26 16:33:07.515253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf0c70710bb'
down_revision: Union[str, None] = 'fda8f097bf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares_feasibility_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_feasibility_workspaces_id'), 'shares_feasibility_workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_shares_feasibility_workspaces_user_id'), 'shares_feasibility_workspaces', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_feasibility_workspaces_user_id'), table_name='shares_feasibility_workspaces')
    op.drop_index(op.f('ix_shares_feasibility_workspaces_id'), table_name='shares_feasibility_workspaces')
    op.drop_table('shares_feasibility_workspaces')
    # ### end Alembic commands ###

