"""added models for feasibility analysis

Revision ID: d87717e1917e
Revises: 88ecaeca117b
Create Date: 2026-03-28 17:58:01.094646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87717e1917e'
down_revision: Union[str, None] = '88ecaeca117b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feasibility_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_projects_id'), 'feasibility_projects', ['id'], unique=False)
    op.create_index(op.f('ix_feasibility_projects_user_id'), 'feasibility_projects', ['user_id'], unique=False)
    op.create_table('feasibility_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['feasibility_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_line_items_id'), 'feasibility_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_feasibility_line_items_project_id'), 'feasibility_line_items', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feasibility_line_items_project_id'), table_name='feasibility_line_items')
    op.drop_index(op.f('ix_feasibility_line_items_id'), table_name='feasibility_line_items')
    op.drop_table('feasibility_line_items')
    op.drop_index(op.f('ix_feasibility_projects_user_id'), table_name='feasibility_projects')
    op.drop_index(op.f('ix_feasibility_projects_id'), table_name='feasibility_projects')
    op.drop_table('feasibility_projects')
    # ### end Alembic commands ###

