"""added tracking of my decisions and discipline

Revision ID: dca970b6b4d8
Revises: 54e4a77a9465
Create Date: 2026-04-13 16:50:39.020896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca970b6b4d8'
down_revision: Union[str, None] = '54e4a77a9465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_discipline_tracks_user_client_id')
    )
    op.create_index(op.f('ix_discipline_tracks_id'), 'discipline_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_discipline_tracks_user_id'), 'discipline_tracks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discipline_tracks_user_id'), table_name='discipline_tracks')
    op.drop_index(op.f('ix_discipline_tracks_id'), table_name='discipline_tracks')
    op.drop_table('discipline_tracks')
    # ### end Alembic commands ###

