"""add time tracker goal/project tables

Revision ID: e6d27e8a9ef3
Revises: 7abd2e311485
Create Date: 2026-07-20 00:56:21.184717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d27e8a9ef3'
down_revision: Union[str, None] = '7abd2e311485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_tracker_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_key', name='uq_time_tracker_goals_user_name_key')
    )
    op.create_index(op.f('ix_time_tracker_goals_id'), 'time_tracker_goals', ['id'], unique=False)
    op.create_index(op.f('ix_time_tracker_goals_user_id'), 'time_tracker_goals', ['user_id'], unique=False)
    op.create_table('time_tracker_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['time_tracker_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_key', name='uq_time_tracker_projects_user_name_key')
    )
    op.create_index(op.f('ix_time_tracker_projects_goal_id'), 'time_tracker_projects', ['goal_id'], unique=False)
    op.create_index(op.f('ix_time_tracker_projects_id'), 'time_tracker_projects', ['id'], unique=False)
    op.create_index(op.f('ix_time_tracker_projects_user_id'), 'time_tracker_projects', ['user_id'], unique=False)
    op.add_column('time_tracker_entries', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('time_tracker_entries', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_time_tracker_entries_goal_id'), 'time_tracker_entries', ['goal_id'], unique=False)
    op.create_index(op.f('ix_time_tracker_entries_project_id'), 'time_tracker_entries', ['project_id'], unique=False)
    op.create_foreign_key(None, 'time_tracker_entries', 'time_tracker_goals', ['goal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'time_tracker_entries', 'time_tracker_projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_tracker_entries', type_='foreignkey')
    op.drop_constraint(None, 'time_tracker_entries', type_='foreignkey')
    op.drop_index(op.f('ix_time_tracker_entries_project_id'), table_name='time_tracker_entries')
    op.drop_index(op.f('ix_time_tracker_entries_goal_id'), table_name='time_tracker_entries')
    op.drop_column('time_tracker_entries', 'project_id')
    op.drop_column('time_tracker_entries', 'goal_id')
    op.drop_index(op.f('ix_time_tracker_projects_user_id'), table_name='time_tracker_projects')
    op.drop_index(op.f('ix_time_tracker_projects_id'), table_name='time_tracker_projects')
    op.drop_index(op.f('ix_time_tracker_projects_goal_id'), table_name='time_tracker_projects')
    op.drop_table('time_tracker_projects')
    op.drop_index(op.f('ix_time_tracker_goals_user_id'), table_name='time_tracker_goals')
    op.drop_index(op.f('ix_time_tracker_goals_id'), table_name='time_tracker_goals')
    op.drop_table('time_tracker_goals')
    # ### end Alembic commands ###

