"""added model functionality for blogs

Revision ID: ef902bdcea82
Revises: c021e93dc4b6
Create Date: 2026-03-30 12:11:54.657582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef902bdcea82'
down_revision: Union[str, None] = 'c021e93dc4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productivity_blog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_productivity_blog_categories_user_name')
    )
    op.create_index(op.f('ix_productivity_blog_categories_id'), 'productivity_blog_categories', ['id'], unique=False)
    op.create_index(op.f('ix_productivity_blog_categories_user_id'), 'productivity_blog_categories', ['user_id'], unique=False)
    op.create_table('productivity_blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_post_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_post_id', name='uq_productivity_blog_posts_user_client_id')
    )
    op.create_index(op.f('ix_productivity_blog_posts_id'), 'productivity_blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_productivity_blog_posts_user_id'), 'productivity_blog_posts', ['user_id'], unique=False)
    op.create_table('productivity_blog_post_categories',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['productivity_blog_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['productivity_blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productivity_blog_post_categories')
    op.drop_index(op.f('ix_productivity_blog_posts_user_id'), table_name='productivity_blog_posts')
    op.drop_index(op.f('ix_productivity_blog_posts_id'), table_name='productivity_blog_posts')
    op.drop_table('productivity_blog_posts')
    op.drop_index(op.f('ix_productivity_blog_categories_user_id'), table_name='productivity_blog_categories')
    op.drop_index(op.f('ix_productivity_blog_categories_id'), table_name='productivity_blog_categories')
    op.drop_table('productivity_blog_categories')
    # ### end Alembic commands ###

