"""added uniqueness for title and name columns for blog and category

Revision ID: f4eb7adbc254
Revises: ef902bdcea82
Create Date: 2026-03-30 12:42:31.792076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4eb7adbc254'
down_revision: Union[str, None] = 'ef902bdcea82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_productivity_blog_categories_user_name', 'productivity_blog_categories', type_='unique')
    op.create_index('uq_productivity_blog_categories_user_lower_name', 'productivity_blog_categories', ['user_id', sa.text('lower(name)')], unique=True)
    op.create_index('uq_productivity_blog_posts_user_lower_title', 'productivity_blog_posts', ['user_id', sa.text('lower(title)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_productivity_blog_posts_user_lower_title', table_name='productivity_blog_posts')
    op.drop_index('uq_productivity_blog_categories_user_lower_name', table_name='productivity_blog_categories')
    op.create_unique_constraint('uq_productivity_blog_categories_user_name', 'productivity_blog_categories', ['user_id', 'name'])
    # ### end Alembic commands ###

