"""added fields in user model for storing body metrics

Revision ID: f6ef931d7442
Revises: 2de75b1c0989
Create Date: 2026-03-23 18:36:45.051072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ef931d7442'
down_revision: Union[str, None] = '2de75b1c0989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'age')
    op.drop_column('users', 'weight_kg')
    # ### end Alembic commands ###

