"""added ability to add stages, and save prospects

Revision ID: fc746422850f
Revises: 7055ff5d8612
Create Date: 2026-03-27 18:40:37.072802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc746422850f'
down_revision: Union[str, None] = '7055ff5d8612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot_prospect_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_prospect_stages_id'), 'plot_prospect_stages', ['id'], unique=False)
    op.create_index(op.f('ix_plot_prospect_stages_user_id'), 'plot_prospect_stages', ['user_id'], unique=False)
    op.create_table('plot_prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phones_json', sa.Text(), nullable=False),
    sa.Column('dealer_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('map_pin', sa.String(), nullable=True),
    sa.Column('plot_size', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['plot_prospect_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_prospects_id'), 'plot_prospects', ['id'], unique=False)
    op.create_index(op.f('ix_plot_prospects_stage_id'), 'plot_prospects', ['stage_id'], unique=False)
    op.create_index(op.f('ix_plot_prospects_user_id'), 'plot_prospects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plot_prospects_user_id'), table_name='plot_prospects')
    op.drop_index(op.f('ix_plot_prospects_stage_id'), table_name='plot_prospects')
    op.drop_index(op.f('ix_plot_prospects_id'), table_name='plot_prospects')
    op.drop_table('plot_prospects')
    op.drop_index(op.f('ix_plot_prospect_stages_user_id'), table_name='plot_prospect_stages')
    op.drop_index(op.f('ix_plot_prospect_stages_id'), table_name='plot_prospect_stages')
    op.drop_table('plot_prospect_stages')
    # ### end Alembic commands ###

