"""added ability to track discipline for each separate day to enable comparison

Revision ID: fda8f097bf7a
Revises: dca970b6b4d8
Create Date: 2026-04-14 10:20:44.909272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda8f097bf7a'
down_revision: Union[str, None] = 'dca970b6b4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_track_daily_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('tracked_on', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['discipline_tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', 'tracked_on', name='uq_discipline_track_daily_counts_user_track_date')
    )
    op.create_index(op.f('ix_discipline_track_daily_counts_id'), 'discipline_track_daily_counts', ['id'], unique=False)
    op.create_index(op.f('ix_discipline_track_daily_counts_track_id'), 'discipline_track_daily_counts', ['track_id'], unique=False)
    op.create_index(op.f('ix_discipline_track_daily_counts_tracked_on'), 'discipline_track_daily_counts', ['tracked_on'], unique=False)
    op.create_index(op.f('ix_discipline_track_daily_counts_user_id'), 'discipline_track_daily_counts', ['user_id'], unique=False)
    op.drop_column('discipline_tracks', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline_tracks', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_discipline_track_daily_counts_user_id'), table_name='discipline_track_daily_counts')
    op.drop_index(op.f('ix_discipline_track_daily_counts_tracked_on'), table_name='discipline_track_daily_counts')
    op.drop_index(op.f('ix_discipline_track_daily_counts_track_id'), table_name='discipline_track_daily_counts')
    op.drop_index(op.f('ix_discipline_track_daily_counts_id'), table_name='discipline_track_daily_counts')
    op.drop_table('discipline_track_daily_counts')
    # ### end Alembic commands ###

